schemes={
 'dev':{
    'domain_default': {'AdministrationPort':7006},
    'admin_server_default': {'ListenPort':7001, 'AdministrationPort':7000},
    'managed_server_template': {'ListenPort':7003},
    'managed_server_cluster_broadcast_channel_template': {'ListenPort':7005},
    'snmp_port_default': 1620,
    'snmp_master_agent_xport_default': 1705,
    'snmp_trap_host_default': 'l2-tamotaapp05.nl.rsg',
    'snmp_trap_port_default': 1620},
 'sys':{
    'domain_default': {'AdministrationPort':7006},
    'admin_server_default': {'ListenPort':7001, 'AdministrationPort':7000},
    'managed_server_template': {'ListenPort':7003},
    'managed_server_cluster_broadcast_channel_template': {'ListenPort':7005},
    'snmp_port_default': 1620,
    'snmp_master_agent_xport_default': 1705,
    'snmp_trap_host_default': 'l2-tamotaapp05.nl.rsg',
    'snmp_trap_port_default': 1620},
 'tst':{
    'domain_default': {'AdministrationPort':7106},
    'admin_server_default': {'ListenPort':7101, 'AdministrationPort':7100},
    'managed_server_template': {'ListenPort':7103},
    'managed_server_cluster_broadcast_channel_template': {'ListenPort':7105},
    'snmp_port_default': 1620,
    'snmp_master_agent_xport_default': 1705,
    'snmp_trap_host_default': 'l2-tamotaapp05.nl.rsg',
    'snmp_trap_port_default': 1620},
 'acc':{
    'domain_default': {'AdministrationPort':7206},
    'admin_server_default': {'ListenPort':7201, 'AdministrationPort':7200},
    'managed_server_template': {'ListenPort':7203},
    'managed_server_cluster_broadcast_channel_template': {'ListenPort':7205},
    'snmp_port_default': 1620,
    'snmp_master_agent_xport_default': 1705,
    'snmp_trap_host_default': 'l2-tamotaapp04.nl.rsg',
    'snmp_trap_port_default': 1620},
 'prd':{
    'domain_default': {'AdministrationPort':7306},
    'admin_server_default': {'ListenPort':7301, 'AdministrationPort':7300},
    'managed_server_template': {'ListenPort':7303},
    'managed_server_cluster_broadcast_channel_template': {'ListenPort':7305},
    'snmp_port_default': 1620,
    'snmp_master_agent_xport_default': 1705,
    'snmp_trap_host_default': 'l2-tamotaapp04.nl.rsg',
    'snmp_trap_port_default': 1620}}